name 'wirbelsturm-storm'
version '1.0.7'
source 'https://github.com/miguno/puppet-storm.git'
author 'Michael G. Noll'
license 'Apache License, Version 2.0'
summary      'Module for managing and configuring Storm'
description  'Module for managing and configuring Storm'
project_page 'https://github.com/miguno/puppet-storm'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-supervisor'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
